export { AnimatedGradient, animatedGradientVariants, type AnimatedGradientProps } from "./animated-gradient";
export { BackgroundPattern, backgroundPatternVariants, type BackgroundPatternProps } from "./background-pattern";
export { Container, containerVariants, type ContainerProps } from "./container";
export { Footer } from "./footer";
export { Hero, type HeroProps } from "./hero";
export { HeroWrapper, heroWrapperVariants, type HeroWrapperProps } from "./hero-wrapper";
export { MaxWidthContainer, maxWidthVariants, type MaxWidthContainerProps } from "./max-width-container";
export { PageContainer, type PageContainerProps } from "./page-container";
export { Section, sectionVariants, type SectionProps } from "./section";
export { Spacing, spacingVariants, type SpacingProps } from "./spacing";
export { Divider, type DividerProps } from "@/components/ui/divider";
